<?php
/**
 * Child Theme Scaffolder
 *
 * Scaffolds a proper child theme according to WordPress standards without online generators.
 *
 * @package SiteCheckupPro
 * @since   1.0.0
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class WPSG_Child_Theme
 */
class WPSG_Child_Theme {

	/**
	 * Check if the active theme is a child theme.
	 *
	 * @return array
	 */
	public static function get_status() {
		$theme = wp_get_theme();

		if ( $theme->parent() ) {
			return array(
				'status'       => 'done',
				'is_child'     => true,
				'theme_name'   => $theme->get( 'Name' ),
				'parent_name'  => $theme->parent()->get( 'Name' ),
				'message'      => sprintf(
					/* translators: 1: theme name, 2: parent theme name */
					__( 'Child theme is active: "%1$s" (Parent: %2$s).', 'site-checkup-pro' ),
					$theme->get( 'Name' ),
					$theme->parent()->get( 'Name' )
				),
			);
		}

		return array(
			'status'       => 'attention',
			'is_child'     => false,
			'theme_name'   => $theme->get( 'Name' ),
			'parent_slug'  => $theme->get_stylesheet(),
			'message'      => sprintf(
				/* translators: %s: theme name */
				__( 'Active theme "%s" is not a child theme. Modifications to parent theme will be overwritten during updates.', 'site-checkup-pro' ),
				$theme->get( 'Name' )
			),
		);
	}

	/**
	 * Scaffold a child theme for the active parent theme.
	 *
	 * @return array
	 */
	public static function scaffold() {
		$theme = wp_get_theme();

		if ( $theme->parent() ) {
			return array(
				'success' => true,
				'message' => __( 'Active theme is already a child theme.', 'site-checkup-pro' ),
			);
		}

		$parent_slug = $theme->get_stylesheet();
		$child_slug  = $parent_slug . '-child';
		$child_dir   = get_theme_root() . '/' . $child_slug;

		if ( is_dir( $child_dir ) ) {
			return array(
				'success' => false,
				'message' => sprintf(
					/* translators: %s: child slug */
					__( 'Directory %s already exists in /wp-content/themes/.', 'site-checkup-pro' ),
					$child_slug
				),
			);
		}

		if ( ! wp_mkdir_p( $child_dir ) ) {
			return array(
				'success' => false,
				'message' => __( 'Failed to create child theme directory. Check filesystem permissions.', 'site-checkup-pro' ),
			);
		}

		// 1. Create style.css
		$style_css = "/*\n" .
			"Theme Name:   " . esc_html( $theme->get( 'Name' ) ) . " Child\n" .
			"Theme URI:    " . esc_url( $theme->get( 'ThemeURI' ) ) . "\n" .
			"Description:  " . esc_html( $theme->get( 'Name' ) ) . " Child Theme generated by Site Checkup Pro\n" .
			"Author:       " . esc_html( $theme->get( 'Author' ) ) . "\n" .
			"Template:     " . $parent_slug . "\n" .
			"Version:      1.0.0\n" .
			"Text Domain:  " . $child_slug . "\n" .
			"*/\n";

		file_put_contents( $child_dir . '/style.css', $style_css );

		// 2. Create functions.php
		$functions_php = "<?php\n" .
			"/**\n" .
			" * " . esc_html( $theme->get( 'Name' ) ) . " Child Theme Functions\n" .
			" */\n\n" .
			"add_action( 'wp_enqueue_scripts', function () {\n" .
			"    wp_enqueue_style( '{$parent_slug}-parent-style', get_template_directory_uri() . '/style.css' );\n" .
			"    wp_enqueue_style( '{$child_slug}-style', get_stylesheet_uri(), array( '{$parent_slug}-parent-style' ) );\n" .
			"} );\n";

		file_put_contents( $child_dir . '/functions.php', $functions_php );

		// Store in option for undo
		update_option( 'wpsg_scaffolded_child_theme', $child_dir );

		return array(
			'success'    => true,
			'child_slug' => $child_slug,
			'themes_url' => admin_url( 'themes.php' ),
			'message'    => sprintf(
				/* translators: 1: child slug, 2: themes url */
				__( 'Child theme "%1$s" successfully created! You can now activate it under <a href="%2$s">Appearance &rarr; Themes</a>.', 'site-checkup-pro' ),
				$child_slug,
				admin_url( 'themes.php' )
			),
		);
	}

	/**
	 * Undo child theme scaffolding if not yet active.
	 *
	 * @return array
	 */
	public static function undo() {
		$child_dir = get_option( 'wpsg_scaffolded_child_theme' );
		if ( empty( $child_dir ) || ! is_dir( $child_dir ) ) {
			return array(
				'success' => false,
				'message' => __( 'No scaffolded child theme found to remove.', 'site-checkup-pro' ),
			);
		}

		$current = wp_get_theme()->get_stylesheet_directory();
		if ( realpath( $current ) === realpath( $child_dir ) ) {
			return array(
				'success' => false,
				'message' => __( 'Cannot delete child theme because it is currently the active theme.', 'site-checkup-pro' ),
			);
		}

		// Security: verify directory is strictly inside theme root
		$real_child  = realpath( $child_dir );
		$real_themes = realpath( get_theme_root() );
		if ( ! $real_child || ! $real_themes || 0 !== strpos( $real_child, $real_themes ) ) {
			return array(
				'success' => false,
				'message' => __( 'Security error: Invalid child theme directory location.', 'site-checkup-pro' ),
			);
		}

		// Delete files
		@unlink( $child_dir . '/style.css' );
		@unlink( $child_dir . '/functions.php' );
		@rmdir( $child_dir );

		delete_option( 'wpsg_scaffolded_child_theme' );

		return array(
			'success' => true,
			'message' => __( 'Scaffolded child theme files removed.', 'site-checkup-pro' ),
		);
	}
}
